// File generated for use in NML servers
Resources
{
	"materials\concrete\concretewall012z.vmt"	"file"
	"materials\concrete\concretewall012z.vtf"	"file"
	"materials\metal\metaltrim02.vmt"	"file"
	"materials\metal\metaltrim02.vtf"	"file"
	"materials\models\props_gameplay\windowed_door.vmt"	"file"
	"materials\models\props_gameplay\windowed_door.vtf"	"file"
	"materials\models\props_gameplay\windowed_door_window.vmt"	"file"
	"materials\models\props_gameplay\windowed_door_window.vtf"	"file"
	"materials\models\props_trainyard\track_cap_base.vmt"	"file"
	"materials\models\props_trainyard\track_cap_base.vtf"	"file"
	"materials\models\props_trainyard\track_cap_blue.vmt"	"file"
	"materials\models\props_trainyard\track_cap_blue.vtf"	"file"
	"materials\models\props_trainyard\track_midcap.vmt"	"file"
	"materials\models\props_trainyard\track_midcap.vtf"	"file"
	"materials\nature\dirtground001_height-ssbump.vtf"	"file"
	"materials\nature\grass_07.vtf"	"file"
	"materials\tile\floor_tile_worn.vmt"	"file"
	"materials\tile\floor_tile_worn.vtf"	"file"
	"materials\winter\blendgraveltograss001.vmt"	"file"
	"materials\winter\blendgraveltograss001_tooltexture.vtf"	"file"
	"materials\winter\rockground010.vtf"	"file"
	"models\props_gameplay\windowed_door.mdl"	"file"
	"models\props_gameplay\windowed_door.dx80.vtx"	"file"
	"models\props_gameplay\windowed_door.dx90.vtx"	"file"
	"models\props_gameplay\windowed_door.sw.vtx"	"file"
	"models\props_gameplay\windowed_door.vvd"	"file"
	"models\props_trainyard\track_midcap.mdl"	"file"
	"models\props_trainyard\track_midcap.dx80.vtx"	"file"
	"models\props_trainyard\track_midcap.dx90.vtx"	"file"
	"models\props_trainyard\track_midcap.sw.vtx"	"file"
	"models\props_trainyard\track_midcap.vvd"	"file"
	"maps\pl_badwater_map_ents.txt"	"file"
}